# Site settings
title: Raccoon Valley Kendo
email: raccoonvalleykendo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Des Moines IA area kendo club.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://raccoonvalleykendo.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  raccoonvalleykendo
future: true

# Build settings
markdown: kramdown

collections:
    - info
    - upcoming

permalink: pretty
